services:
  - type: web
    name: pollo-loco-supervision
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        value: postgresql://neondb_owner:1hLdOZPLDwii@ep-crimson-pond-a5l7mzwx.us-east-2.aws.neon.tech/neondb?sslmode=require
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: TELEGRAM_BOT_TOKEN
        value: 8341799056:AAFvMMPzuplDDsOM07m5ANI5WVCATchBPeY
      - key: RENDER_EXTERNAL_URL
        value: https://pollo-loco-supervision.onrender.com
      - key: START_BOT
        value: true