// MAPEO COMPLETO DE SUCURSALES
// Total: 77 sucursales mapeadas

const sucursalMapping = {
  'aeropuerto': '61 - Aeropuerto (Tampico)',
  'alcala': '78 - Alcala',
  'allende': '32 - Allende',
  'anahuac': '9 - Anahuac',
  'anzalduas': '73 - Anzalduas',
  'apodaca centro': '36 - Apodaca Centro',
  'avenida del niño': '68 - Avenida del Niño',
  'aztlan': '14 - Aztlan',
  'barragan': '10 - Barragan',
  'boulevard morelos': '77 - Boulevard Morelos',
  'cadereyta': '26 - Cadereyta',
  'campestre': '46 - Campestre',
  'carrizo': '30 - Carrizo',
  'centrito valle': '71 - Centrito Valle',
  'centro': '67 - Centro (Matamoros)',
  'chapultepec': '21 - Chapultepec',
  'coahuila comidas': '70 - Coahuila Comidas',
  'concordia': '12 - Concordia',
  'constituyentes': '51 - Constituyentes',
  'eloy cavazos': '33 - Eloy Cavazos',
  'escobedo': '13 - Escobedo',
  'eulalio gutierrez': '55 - Eulalio Gutierrez',
  'exposicion': '24 - Exposicion',
  'felix gomez': '5 - Felix U. Gomez',
  'felix u. gomez': '5 - Felix U. Gomez',
  'garcia': 'Sucursal GC - Garcia',
  'gomez morin': '38 - Gomez Morin',
  'gonzalitos': '8 - Gonzalitos',
  'guasave': '23 - Guasave',
  'guerrero': '28 - Guerrero',
  'guerrero 2': '80 - Guerrero 2 (Ruelas)',
  'harold pape': '57 - Harold R. Pape',
  'harold r. pape': '57 - Harold R. Pape',
  'hidalgo': '74 - Hidalgo (Reynosa)',
  'huerta': '64 - Huerta',
  'independencia': '42 - Independencia',
  'juarez': '25 - Juarez',
  'la huasteca': '7 - La Huasteca',
  'las quintas': '31 - Las Quintas',
  'lauro villar': '66 - Lauro Villar',
  'lazaro cardenas': '62 - Lazaro Cardenas (Morelia)',
  'libramiento': '75 - Libramiento (Reynosa)',
  'lincoln': '11 - Lincoln',
  'linda vista': '18 - Linda Vista',
  'luis echeverria': '56 - Luis Echeverria',
  'madero': '63 - Madero (Morelia)',
  'matamoros': '3 - Matamoros',
  'montemorelos': '34 - Montemorelos',
  'pablo livas': '29 - Pablo Livas',
  'patio': '50 - Patio',
  'pedro cardenas': '65 - Pedro Cardenas',
  'pino suarez': '1 - Pino Suarez',
  'plaza 1500': '40 - Plaza 1500',
  'plaza 3601': '59 - Plaza 3601',
  'pueblito': '49 - Pueblito',
  'puerto rico': '69 - Puerto Rico',
  'ramos arizpe': '54 - Ramos Arizpe',
  'reforma': '81 - Reforma (Ruelas)',
  'refugio': '48 - Refugio',
  'revolucion': '43 - Revolucion',
  'rio bravo': '79 - Rio Bravo',
  'romulo garza': '17 - Romulo Garza',
  'ruiz cortinez': '15 - Ruiz Cortinez',
  'sabinas hidalgo': '72 - Sabinas Hidalgo',
  'san antonio': '47 - San Antonio',
  'santa catarina': 'Sucursal SC - Santa Catarina',
  'santiago': '27 - Santiago',
  'satelite': '22 - Satelite',
  'senderos': '44 - Senderos',
  'solidaridad': '16 - Solidaridad',
  'stiva': '37 - Stiva',
  'tecnológico': '20 - Tecnológico',
  'triana': '45 - Triana',
  'universidad': '58 - Universidad (Tampico)',
  'valle soleado': '19 - Valle Soleado',
  'vasconcelos': '41 - Vasconcelos',
  'venustiano carranza': '52 - Venustiano Carranza'
};

// EJEMPLOS DE USO:
// "triana" → "45 - Triana"
// "senderos" → "44 - Senderos"
// "harold pape" → "57 - Harold R. Pape"
// "pino suarez" → "1 - Pino Suarez"
